fail_fast: true
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: '0.11.2'  # add version here
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: xenon
        name: xenon
        entry: bash -c "uv run xenon -a $(uv run python -c \"import tomllib; f = open('pyproject.toml','rb') ; data =  tomllib.load(f); f.close(); print(data['tool']['quality']['mccabe']['average'])\") -b $(uv run python -c \"import tomllib; f = open('pyproject.toml','rb') ; data =  tomllib.load(f); f.close(); print(data['tool']['quality']['mccabe']['block'])\") -m $(uv run python -c \"import tomllib; f = open('pyproject.toml','rb') ; data =  tomllib.load(f); f.close(); print(data['tool']['quality']['mccabe']['module'])\") . "
        language: system
        types: [ file, python ]
